[package]
name = "rayonix-consensus"
version = "0.1.0"
edition = "2021"
authors = ["RAYONIX Chain Dev Team <team@rayonix.org>"]
description = "Hybrid Proof-of-Stake + Proof-of-Time-Lived (PoTL) consensus engine for the RAYONIX blockchain."
license = "MIT OR Apache-2.0"
repository = "https://github.com/yourusername/RAYONIX-CHAIN"
readme = "README.md"

[lib]
name = "rayonix_consensus"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]  # 'cdylib' enables Python/C interop via FFI or PyO3

[dependencies]
# === Core async/runtime dependencies ===
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
async-trait = "0.1"

# === Math, Probability, and Statistics ===
rand = "0.8"
rand_distr = "0.4"
statrs = "0.16"

# === Cryptography and Signatures ===
bls12_381 = "0.8"
bls-signatures = "0.14"
sha2 = "0.10"
merlin = "3.0"

# === Serialization / Deserialization ===
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# === Concurrency, Sync, Parallelism ===
rayon = "1.10"
parking_lot = "0.12"
once_cell = "1.19"

# === Logging and Tracing ===
log = "0.4"
env_logger = "0.11"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# === Optional: PyO3 for Python bindings (if integrating with Python layer) ===
pyo3 = { version = "0.22", features = ["extension-module"] }

[dev-dependencies]
criterion = "0.5"   # benchmarking
proptest = "1.4"    # property-based testing

[features]
default = ["core", "mechanisms", "security", "economics", "state", "governance"]
python-bindings = ["pyo3"]

[profile.release]
opt-level = "z"     # smaller binaries
lto = true
codegen-units = 1